### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RexWzh** [RexWzh/rubik_cube.py#4]
- [x] ~允许非标准状态的魔方中心：直接调用 `Kociemba` 会报错，需手动转化格式。~
        ~https://github.com/RexWzh/rubik_cube.py/blob/e2395e21beade883dfb0f9fc06230a5da083281d/src/rubik.py#L67~
- [x] 颜色识别：当前通过预设变量 `colors` 识别颜色，更通用的方式是对小块颜色进行分类，然后建立当前颜色到 `Kociemba` 默认颜色的对应
        https://github.com/RexWzh/rubik_cube.py/blob/e2395e21beade883dfb0f9fc06230a5da083281d/src/data.py#L11
- [ ] 修复 Kociemba 模块的问题
